### ISSUE TITLE
Feature request: Add VIP to buff checker

### ISSUE THREAD

**Issue by AnotherByteInTheBucket** [jaredcrystal/BuffChecker#1]
Just a nice to have if the buff checker could also check for VIP buff. Though, I understand if it is undesirable to add due to not always being available but seem VIP buff is pretty common from events now.
![image](https://github.com/jaredcrystal/BuffChecker/assets/169215050/ae10ccc3-efe6-44b1-8535-19b814d1e608)

**Comment by jaredcrystal** [comment]
Yeah, I've gone back and forth on VIP buff. I hadn't added it before now since it's not always available, but maybe I'll add it in its own "Event" category so it's clear. Thanks for the idea!

**Comment by jaredcrystal** [comment]
I added VIP as per your suggestion

**Comment by AnotherByteInTheBucket** [comment]
Many thanks, great tool.
